### ISSUE TITLE
Feed denylist

### ISSUE THREAD

**Issue by zeek-zag** [mgnsk/FreshRSS-AutoTTL#11]
Loving what this plugin does but I'm wondering if it's possible to include a denylist so we can exclude feeds that absolutely need to be refreshed more often. This would be mighty useful for feeds from status pages like [Quad9](https://uptime.quad9.net/) or [Cloudflare](https://www.cloudflarestatus.com/).

Currently, if an incident happens the feed won't get refreshed until it reaches its maximum TTL which is not ideal (:

**Comment by mgnsk** [comment]
It could work like this: if the feed has the TTL setting `By default`, use AutoTTL, otherwise use the explicit TTL configured by feed.

The plugin already recommends setting each feed to use the default TTL, I could make this a requirement for AutoTTL to work.

**Comment by zeek-zag** [comment]
Yep, that would be sweet. All my feeds are following your recommended `by default` TTL settings anyway.
