### ISSUE TITLE
No automatic refresh

### ISSUE THREAD

**Issue by tobiasholle** [mgnsk/FreshRSS-AutoTTL#15]
Hi, I installed the extension but it is unfortunately not working. Is there anything I need to take care of before it is actually implemented?

**Comment by mgnsk** [comment]
Do your feeds update without using this plugin? Can you check the statistics table in plugin options, are there any feeds where `Time until next update` is empty? This would mean that the time to update the feed has come but the cron has not run yet.

**Comment by tobiasholle** [comment]
They do but only if I update manually, it is not empty (see. picture)

<img width="436" alt="Capture d’écran 2024-10-06 à 08 52 56" src="https://github.com/user-attachments/assets/5cbcbec6-7d1c-4a0c-a803-6b1502e81e02">

**Comment by mgnsk** [comment]
Make sure your AutoTTL's Max TTL setting is longer than FreshRSS's TTL (from Configuration -> Archiving).

A good default is to use `1d` for AutoTTL's Max TTL and `20min` for FreshRSS TTL. This way faster feeds can still benefit from the 20min rate but slower feeds fall somewhere between 20min and 1d.

I'll try to come up with some solution that would show perhaps a warning when those values are not configured correctly.

**Comment by tobiasholle** [comment]
Thank you. I edited the times. Nevertheless, as you can see in the screenshot, the updates are not carried out for the Feeds (probably only the ones with the maximum TLL of 12 hours, couldn't verify by now but according to the changes in the TLL update times). 
<img width="423" alt="Capture d’écran 2024-10-07 à 07 07 10" src="https://github.com/user-attachments/assets/0c671631-e9fa-45e1-8658-922e9ef78cdc">

**Comment by tobiasholle** [comment]
You have any idea there? It's still not updating the feeds automatically and I therefore have to do it manually which was not the purpose.

**Comment by mgnsk** [comment]
> You have any idea there? It's still not updating the feeds automatically and I therefore have to do it manually which was not the purpose.

Sorry, haven't got the time yet.

Are you sure your cron is set up correctly? Do the feeds automatically update without this plugin enabled?

Any way, if it's an issue with this plugin, the first course of action would be to write a suite of tests which I've put off for too long.

**Comment by tobiasholle** [comment]
I didn't really get it going properly. The feeds update automatically and I'll just leave it like that. I'm not enough an expert to try out too much and break everything... 🙈

**Comment by mgnsk** [comment]
> I didn't really get it going properly. The feeds update automatically and I'll just leave it like that. I'm not enough an expert to try out too much and break everything... 🙈

Can you update to [v0.5.6](https://github.com/mgnsk/FreshRSS-AutoTTL/releases/tag/v0.5.6), enable debug logging by setting `'environment' => 'development'` in FreshRSS's `data/config.php` file and check the statistics table and logs again after some time?

The logs should eventually tell exactly what happened to each feed for every decision made by AutoTTL.

**Comment by mgnsk** [comment]
Fixed in https://github.com/mgnsk/FreshRSS-AutoTTL/releases/tag/v0.5.7.
