### ISSUE TITLE
What exacly does AutoTTL do?

### ISSUE THREAD

**Issue by Fdr3iZzz** [mgnsk/FreshRSS-AutoTTL#8]
Hey, what exacly does AutoTTL do? As I understand it, it refreshes the feeds based on how frequent they are, but I now let it run for 2 days or so, and it still is not set correctly. I had to manually refresh all feeds every time.
Isn't it also easier to just update all feeds about ever 30min?
Thanks for the answere, I'm sadly very new to RSS...

**Comment by vonguyenkhang** [comment]
> I had to manually refresh all feeds every time.

Make sure you have setup the [Automatic update with cron](https://freshrss.github.io/FreshRSS/en/users/09_refreshing_feeds.html#automatic-update-with-cron) correctly. Double check the cron log to make sure that the cron job indeed executed. After that is working then we can talk about AutoTTL.

**Comment by vonguyenkhang** [comment]
> I'm sadly very new to RSS...
- Imagine FreshRSS is your physical mailbox, and the RSS feeds are the contents of the mailbox.
- Ideally, you want to get the contents of the physical mailbox as soon as they are available, but in practice you **_don't want to waste_** your time/life/effort checking the physical mailbox every minute. Hence, there's a **_balance/compromise_** between Content Freshness, Efficiency and Resources, Importance of Content, etc. 
- In the digital world, refreshing your RSS feeds too frequently may also cause the feed sources/websites to ban/block you temporarily.
- In FreshRSS, there's a global default setting to decide how frequently the feeds are refreshed, let's call it "_Default TTL_". 
- FreshRSS also allow you to individually configure how frequent each feed should be refreshed. This individual setting overwrites the _Default TTL_.
- The traditional method is to set a _Default TTL_ that is suitable for most of your RSS feeds, and set the individual TTLs for some special RSS feeds that you want to be updated faster (or slower) than the _Default TTL_. This method works, but it's tedious.
- So here comes _AutoTTL_: A FreshRSS extension for automatic feed refresh TTL based on the average frequency of entries. It is recommended to configure each feed to use the default TTL and set the default TTL to 1h. This will let AutoTTL work most efficiently. (from [README](https://github.com/mgnsk/FreshRSS-AutoTTL/blob/main/README.md))

**Comment by vonguyenkhang** [comment]
> Isn't it also easier to just update all feeds about ever 30min?
- Imagine FreshRSS is your physical mailbox, and the RSS feeds are the contents of the mailbox.
- Ideally, you want to get the contents of the physical mailbox as soon as they are available, but in practice you **_don't want to waste_** your time/life/effort checking the physical mailbox every minute. Hence, there's a **_balance/compromise_** between Content Freshness, Efficiency and Resources, Importance of Content, etc. 
- In the digital world, refreshing your RSS feeds too frequently may also cause the feed sources/websites to ban/block you temporarily.
- In FreshRSS, there's a global default setting to decide how frequently the feeds are refreshed, let's call it "_Default TTL_". 
- FreshRSS also allow you to individually configure how frequent each feed should be refreshed. This individual setting overwrites the _Default TTL_.
- The traditional method is to set a _Default TTL_ that is suitable for most of your RSS feeds, and set the individual TTLs for some special RSS feeds that you want to be updated faster (or slower) than the _Default TTL_. This method works, but it's tedious.
- So here comes _AutoTTL_: A FreshRSS extension for automatic feed refresh TTL based on the average frequency of entries. It is recommended to configure each feed to use the default TTL and set the default TTL to 1h. This will let AutoTTL work most efficiently. (from [README](https://github.com/mgnsk/FreshRSS-AutoTTL/blob/main/README.md))

**Comment by vonguyenkhang** [comment]
> Isn't it also easier to just update all feeds about ever 30min?
- Imagine FreshRSS is your physical mailbox, and the RSS feeds are the contents of the mailbox.
- Ideally, you want to get the contents of the physical mailbox as soon as they are available, but in practice you **_don't want to waste_** your time/life/effort checking the physical mailbox every minute. Hence, there's a **_balance/compromise_** between Content Freshness, Efficiency and Resources, Importance of Content, etc. 
- In the digital world, refreshing your RSS feeds too frequently may also cause the feed sources/websites to ban/block you temporarily.
- In FreshRSS, there's a global default setting to decide how frequently the feeds are refreshed, let's call it "_Default TTL_". 
- FreshRSS also allow you to individually configure how frequent each feed should be refreshed. This individual setting overwrites the _Default TTL_.
- The traditional method is to set a _Default TTL_ that is suitable for most of your RSS feeds, and set the individual TTLs for some special RSS feeds that you want to be updated more frequently (or less frequently) than the _Default TTL_. This method works, but it's tedious.
- So here comes _AutoTTL_: A FreshRSS extension for automatic feed refresh TTL based on the average frequency of entries. It is recommended to configure each feed to use the default TTL and set the default TTL to 1h. This will let AutoTTL work most efficiently. (from [README](https://github.com/mgnsk/FreshRSS-AutoTTL/blob/main/README.md))

**Comment by vonguyenkhang** [comment]
> Isn't it also easier to just update all feeds about ever 30min?
- Imagine FreshRSS is your physical mailbox, and the RSS feeds are the contents of the mailbox.
- Ideally, you want to get the contents of the physical mailbox as soon as they are available, but in practice you **_don't want to waste_** your time/life/effort checking the physical mailbox every minute. Hence, there's a **_balance/compromise_** between Content Freshness, Efficiency and Resources, Importance of Content, etc. 
- In the digital world, refreshing your RSS feeds too frequently may also cause the feed sources/websites to ban/block you temporarily.
- In FreshRSS, there's a global default setting to decide how frequently the feeds are refreshed, let's call it "_Default TTL_". 
- FreshRSS also allow you to individually configure how frequent each feed should be refreshed. This individual setting overwrites the _Default TTL_.
- The traditional method is to set a _Default TTL_ that is suitable for most of your RSS feeds, and set the individual TTLs for some special RSS feeds that you want to be updated more frequently (or less frequently) than the _Default TTL_. This method works, but it's tedious.
- So here comes _AutoTTL_: A FreshRSS extension for automatic feed refresh TTL based on the average frequency of entries.

**Comment by mgnsk** [comment]
That's correct. It makes the feeds update less frequently than they normally would, refreshing them when it is most likely a new entry has been posted, reducing the number feed requests.

It covers the usecase when you subscribe to hundreds of feeds from the same website, for example content and news aggregation sites where each category is a separate feed. I set my **_Default TTL_** to 20min and **_Max TTL_** to 1day to maximize the temporal distribution of feed requests.
